language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy"

install:
    - pip install -r requirements/ci.txt

script: nosetests --with-cov -v -w tests
after_success:
    - coveralls
