language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    - pip install -r ci_requirements.txt --use-mirrors

script: python setup.py nosetests --with-cov -v -w tests
after_success:
    - coveralls
cache:
    directories:
        - $HOME/virtualenv/python2.6/site-packages 
        - $HOME/virtualenv/python2.7/site-packages 
        - $HOME/virtualenv/python3.2/site-packages 
        - $HOME/virtualenv/python3.3/site-packages 
        - $HOME/virtualenv/pypy/site-packages 
