language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - pip install -r ci_requirements.txt --use-mirrors

script: python setup.py nosetests --with-cov -v
after_success:
    - coveralls
