language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    - pip install -r ci_requirements.txt --use-mirrors

script: nosetests --with-cov -v -w tests 
after_success:
    - coveralls
